ARG BUILD_MODE=ODH

ARG BASE_IMAGE_ODH=registry.access.redhat.com/ubi9/go-toolset:1.24
ARG BASE_IMAGE_RHOAI=registry.access.redhat.com/ubi9/go-toolset@sha256:71f121a44270e46a17a548d6b92096a1a0fb56db44927ad318d095177d6dce4b
ARG BASE_IMAGE=${BASE_IMAGE_${BUILD_MODE}}
FROM ${BASE_IMAGE} AS builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY . .

# Build
USER root
RUN CGO_ENABLED=1 GOEXPERIMENT=strictfipsruntime GOOS=linux GO111MODULE=on go build -a -o manager cmd/trainer-controller-manager/main.go

# Runtime
ARG BASE_IMAGE_1_ODH=registry.access.redhat.com/ubi9/ubi-minimal:latest
ARG BASE_IMAGE_1_RHOAI=registry.access.redhat.com/ubi9/ubi-minimal@sha256:90bd85dcd061d1ad6dbda70a867c41958c04a86462d05c631f8205e8870f28f8
ARG BASE_IMAGE_1=${BASE_IMAGE_1_${BUILD_MODE}}
FROM ${BASE_IMAGE_1}

WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532
ENTRYPOINT ["/manager"]
# >>> [RHOAI] <<<

LABEL com.redhat.component="odh-trainer-rhel9" \
      name="rhoai/odh-trainer-rhel9" \
      description="odh-trainer" \
      summary="odh-trainer" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-trainer" \
      io.k8s.description="odh-trainer" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
# >>> [END RHOAI] <<<
