FROM registry.access.redhat.com/ubi9/python-312

USER 0

RUN yum install -y \
        wget \
        jq \
        tar \
        make \
        podman \
        fuse-overlayfs \
        slirp4netns \
        shadow-utils \
    && yum clean all

# Install oc + kubectl
RUN wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz && \
    tar xvf openshift-client-linux.tar.gz && \
    chmod +x oc kubectl && \
    mv oc kubectl /usr/local/bin/

# Install yq v4 directly into project bin directory
ENV YQ_VERSION=v4.44.1

RUN curl -L https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 \
    -o /tmp/yq && \
    chmod +x /tmp/yq

WORKDIR /opt/app-root/src

RUN mkdir -p bin && \
    cp /tmp/yq bin/yq


