ARG BUILD_MODE=ODH

# Build the inference-agent binary
ARG BASE_IMAGE_ODH=registry.access.redhat.com/ubi9/go-toolset:1.25
ARG BASE_IMAGE_RHOAI=registry.access.redhat.com/ubi9/go-toolset:1.24
ARG BASE_IMAGE=${BASE_IMAGE_${BUILD_MODE}}
FROM ${BASE_IMAGE} AS builder

# Copy in the go src
WORKDIR /go/src/github.com/kserve/kserve
COPY go.mod  go.mod
COPY go.sum  go.sum

RUN go mod download

COPY cmd/    cmd/
COPY pkg/    pkg/

# Build
USER root
# >>> [ODH] <<<
RUN CGO_ENABLED=0 GOOS=linux GOFLAGS=-mod=mod go build -a -o agent ./cmd/agent

# Generate third-party licenses
COPY LICENSE LICENSE
RUN go install github.com/google/go-licenses@latest
# Forbidden Licenses: https://github.com/google/licenseclassifier/blob/e6a9bb99b5a6f71d5a34336b8245e305f5430f99/license_type.go#L341
RUN /opt/app-root/src/go/bin/go-licenses check ./cmd/... ./pkg/... --disallowed_types="forbidden,unknown"
RUN /opt/app-root/src/go/bin/go-licenses save --save_path third_party/library ./cmd/agent
# >>> [END ODH] <<<
# >>> [RHOAI] <<<
RUN CGO_ENABLED=1 GOOS=${TARGETOS} GOARCH=${TARGETARCH} GOFLAGS=-mod=mod GOEXPERIMENT=strictfipsruntime go build -tags strictfipsruntime -a -o agent ./cmd/agent
# >>> [END RHOAI] <<<

# Copy the inference-agent into a thin image
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

RUN microdnf install -y --disablerepo=* --enablerepo=ubi-9-baseos-rpms shadow-utils && \
    microdnf clean all && \
    useradd kserve -m -u 1000
RUN microdnf remove -y shadow-utils

# >>> [ODH] <<<
COPY --from=builder /go/src/github.com/kserve/kserve/third_party /third_party
# >>> [END ODH] <<<
# >>> [RHOAI] <<<
COPY third_party_agent/ third_party/
# >>> [END RHOAI] <<<

WORKDIR /ko-app

COPY --from=builder /go/src/github.com/kserve/kserve/agent /ko-app/
USER 1000:1000

ENTRYPOINT ["/ko-app/agent"]
# >>> [RHOAI] <<<

LABEL com.redhat.component="odh-kserve-agent" \
      name="odh-kserve-agent" \
      description="odh-kserve-agent" \
      summary="odh-kserve-agent" \
      io.k8s.display-name="odh-kserve-agent" \
      io.k8s.description="odh-kserve-agent"
# >>> [END RHOAI] <<<
