ARG BUILD_MODE=ODH

# Build the manager binary
ARG BASE_IMAGE_ODH=registry.access.redhat.com/ubi9/go-toolset:1.25
ARG BASE_IMAGE_RHOAI=registry.access.redhat.com/ubi9/go-toolset@sha256:3cdf0d1e8d8601c89fe3070d7aa63a54d1aaf049ba55fba314f6358b1d95a2f9
ARG BASE_IMAGE=${BASE_IMAGE_${BUILD_MODE}}
FROM ${BASE_IMAGE} AS builder

# Copy in the go src
WORKDIR /go/src/github.com/kserve/kserve
COPY go.mod  go.mod
COPY go.sum  go.sum

RUN go mod download

COPY cmd/    cmd/
COPY pkg/    pkg/

# Build
# >>> [ODH] <<<
ARG GOTAGS=""
# >>> [END ODH] <<<
# >>> [RHOAI] <<<
ARG GOTAGS="distro"
# >>> [END RHOAI] <<<
RUN CGO_ENABLED=0 GOOS=linux go build -tags "${GOTAGS}" -a -o manager ./cmd/llmisvc

# Generate third-party licenses
COPY LICENSE LICENSE
RUN if [ "$BUILD_MODE" = "ODH" ]; then \
      go install github.com/google/go-licenses@latest ; \
      # Forbidden Licenses: https://github.com/google/licenseclassifier/blob/e6a9bb99b5a6f71d5a34336b8245e305f5430f99/license_type.go#L341 ; \
      /opt/app-root/src/go/bin/go-licenses check ./cmd/... ./pkg/... --disallowed_types="forbidden,unknown" ; \
      /opt/app-root/src/go/bin/go-licenses save --save_path third_party/library ./cmd/llmisvc ; \
    fi

# Copy the controller-manager into a thin image
ARG BASE_IMAGE_1_ODH=gcr.io/distroless/static:nonroot
ARG BASE_IMAGE_1_RHOAI=registry.access.redhat.com/ubi9/ubi-minimal:latest
ARG BASE_IMAGE_1=${BASE_IMAGE_1_${BUILD_MODE}}
FROM ${BASE_IMAGE_1}
COPY --from=builder /go/src/github.com/kserve/kserve/manager /
# >>> [ODH] <<<
ENTRYPOINT ["/manager"]# >>> [END ODH] <<<
# >>> [RHOAI] <<<
ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-kserve-llmisvc-controller" \
      name="managed-open-data-hub/odh-kserve-llmisvc-controller" \
      description="odh-kserve-llmisvc-controller" \
      summary="odh-kserve-llmisvc-controller" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-kserve-llmisvc-controller" \
      io.k8s.description="odh-kserve-llmisvc-controller" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
# >>> [END RHOAI] <<<
