ARG BUILD_MODE=ODH

# Copyright 2021-2024 The Kubeflow Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build arguments
ARG SOURCE_CODE=.
# >>> [ODH] <<<
ARG FIPS_ENABLED=1
ARG TARGETOS=linux
ARG TARGETARCH=amd64
# >>> [END ODH] <<<

ARG BASE_IMAGE_ODH=registry.access.redhat.com/ubi9/go-toolset:1.25.7-1771417345
ARG BASE_IMAGE_RHOAI=registry.access.redhat.com/ubi9/go-toolset:1.24@sha256:6234f572204d672a0ee0686d748fbb9b7b05679368bf0d7a4446e13970e58060
ARG BASE_IMAGE=${BASE_IMAGE_${BUILD_MODE}}
FROM ${BASE_IMAGE} AS builder


## Build args to be used at this step
ARG SOURCE_CODE
# >>> [ODH] <<<
ARG FIPS_ENABLED
# >>> [END ODH] <<<
ARG TARGETOS
ARG TARGETARCH
RUN if [ "$BUILD_MODE" = "ODH" ]; then \
       ; \
    fi
## Switch to root as required for some operations
USER root

COPY ${SOURCE_CODE}/go.mod ./
COPY ${SOURCE_CODE}/go.sum ./
# >>> [ODH] <<<
COPY ${SOURCE_CODE}/kubernetes_platform/go.mod ./kubernetes_platform/go.mod
COPY ${SOURCE_CODE}/api/go.mod ./api/go.mod

RUN GO111MODULE=on go mod download
# >>> [END ODH] <<<

# Copy the source
COPY ${SOURCE_CODE}/ ./

RUN if [ "$BUILD_MODE" = "RHOAI" ]; then \
      GO111MODULE=on CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} GOEXPERIMENT=strictfipsruntime go build -tags 'netgo strictfipsruntime'  -o /bin/driver ./backend/src/v2/cmd/driver/*.go ; \
    else \
      # FIPS_ENABLED=1 (default): FIPS-compliant build with strictfipsruntime (requires CGO) ; \
      # FIPS_ENABLED=0: Non-FIPS build for local development on Apple Silicon (pure Go, no CGO) ; \
      if [ "${FIPS_ENABLED}" = "0" ]; then \ ; \
      GO111MODULE=on CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \ ; \
      go build -tags netgo -o /bin/driver ./backend/src/v2/cmd/driver/*.go; \ ; \
      elif [ "${FIPS_ENABLED}" = "1" ]; then \ ; \
      GO111MODULE=on CGO_ENABLED=1 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \ ; \
      GOEXPERIMENT=strictfipsruntime \ ; \
      go build -tags 'netgo strictfipsruntime' -o /bin/driver ./backend/src/v2/cmd/driver/*.go; \ ; \
      else \ ; \
      echo "ERROR: FIPS_ENABLED must be '0' or '1', got '${FIPS_ENABLED}'" && exit 1; \ ; \
      fi ; \
    fi

ARG BASE_IMAGE_1_ODH=registry.access.redhat.com/ubi9/ubi-minimal:9.5
ARG BASE_IMAGE_1_RHOAI=registry.access.redhat.com/ubi9/ubi-minimal@sha256:83006d535923fcf1345067873524a3980316f51794f01d8655be55d6e9387183
ARG BASE_IMAGE_1=${BASE_IMAGE_1_${BUILD_MODE}}
FROM ${BASE_IMAGE_1}

WORKDIR /bin

COPY --from=builder /bin/driver /bin/driver
RUN chmod +x /bin/driver

# >>> [ODH] <<<
USER 65534

# >>> [END ODH] <<<
ENTRYPOINT ["/bin/driver"]

# >>> [ODH] <<<
LABEL name="ds-pipelines-driver" \
      summary="DSP Driver"
# >>> [END ODH] <<<
# >>> [RHOAI] <<<
LABEL com.redhat.component="odh-ml-pipelines-driver-container" \
      name="managed-open-data-hub/odh-ml-pipelines-driver-rhel8" \
      description="odh-ml-pipelines-driver" \
      summary="odh-ml-pipelines-driver" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-ml-pipelines-driver" \
      io.k8s.description="odh-ml-pipelines-driver" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
# >>> [END RHOAI] <<<
