ARG BUILD_MODE=ODH

# >>> [RHOAI] <<<
# Build arguments
ARG SOURCE_CODE=.

# >>> [END RHOAI] <<<
# Build the manager binary
ARG BASE_IMAGE_ODH=registry.access.redhat.com/ubi8/go-toolset:1.23
ARG BASE_IMAGE_RHOAI=registry.access.redhat.com/ubi9/go-toolset:1.23@sha256:381fb72f087a07432520fa93364f66b5981557f1dd708f3c4692d6d0a76299b3
ARG BASE_IMAGE=${BASE_IMAGE_${BUILD_MODE}}
FROM ${BASE_IMAGE} AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY cmd/ cmd/
COPY api/ api/
COPY controllers/ controllers/

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
USER root
RUN if [ "$BUILD_MODE" = "RHOAI" ]; then \
      CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} GOEXPERIMENT=strictfipsruntime go build -tags strictfipsruntime -a -o manager cmd/main.go ; \
    else \
      CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o manager cmd/main.go ; \
    fi

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
ARG BASE_IMAGE_1_ODH=registry.access.redhat.com/ubi8/ubi-minimal:latest
ARG BASE_IMAGE_1_RHOAI=registry.access.redhat.com/ubi9/ubi-minimal@sha256:c7d44146f826037f6873d99da479299b889473492d3c1ab8af86f08af04ec8a0
ARG BASE_IMAGE_1=${BASE_IMAGE_1_${BUILD_MODE}}
FROM ${BASE_IMAGE_1}
WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532

ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-trustyai-service-operator-container" \
      name="managed-open-data-hub/odh-trustyai-service-operator-rhel8" \
RUN if [ "$BUILD_MODE" = "RHOAI" ]; then \
      description="The TrustyAI Operator manages TrustyAI deployments within a k8s cluster" \ ; \
    else \
      version="${CI_CONTAINER_VERSION}" \ ; \
    fi
      summary="odh-trustyai-service-operator" \
RUN if [ "$BUILD_MODE" = "RHOAI" ]; then \
      maintainer="['managed-open-data-hub@redhat.com']" \ ; \
    fi
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-trustyai-service-operator" \
RUN if [ "$BUILD_MODE" = "RHOAI" ]; then \
      io.k8s.description="odh-trustyai-service-operator" \ ; \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf" ; \
    else \
      maintainer="['managed-open-data-hub@redhat.com']" \ ; \
      description="The TrustyAI Operator manages TrustyAI deployments within a k8s cluster" \ ; \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf" ; \
    fi
