# Unified Dockerfile – select build mode via BUILD_MODE arg
ARG BUILD_MODE=ODH

# ============================================================
# ODH Build
# ============================================================
ARG VENV_PATH=/prod_venv

## Builder
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS odh-builder

# Install Python and dependencies
RUN microdnf install -y --setopt=ubi-9-appstream-rpms.module_hotfixes=1 --disablerepo=* \
    --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms \
      python3.11-devel \
      python3.11 \
      gcc \
      libffi-devel \
      openssl-devel \
      krb5-workstation \
      krb5-libs  \
      krb5-devel  \
      gcc-c++ \
      make tar \
    && microdnf clean all \
    && alternatives --install /usr/bin/python python /usr/bin/python3.11 1

RUN microdnf update -y && microdnf clean all

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    ln -s /root/.local/bin/uv /usr/local/bin/uv

# Activate virtual env
ARG VENV_PATH
ENV VIRTUAL_ENV=${VENV_PATH}
RUN uv venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install Python dependencies
COPY storage/pyproject.toml storage/uv.lock storage/
RUN cd storage && uv sync --active --no-cache 

COPY storage storage
RUN cd storage && uv pip install . --no-cache 

# Install Kerberos-related packages
RUN uv pip install --no-cache-dir krbcontext==0.10 hdfs~=2.6.0 requests-kerberos==0.14.0

# Generate third-party licenses
COPY pyproject.toml pyproject.toml
COPY third_party/pip-licenses.py pip-licenses.py
# TODO: Remove this when upgrading to python 3.11+
RUN uv pip install --no-cache-dir tomli
RUN mkdir -p third_party/library && python3 pip-licenses.py


## Runtime
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS odh-prod

# Activate virtual env
ARG VENV_PATH
ENV VIRTUAL_ENV=${VENV_PATH}
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN microdnf install -y --setopt=ubi-9-appstream-rpms.module_hotfixes=1 --disablerepo=* \
    --enablerepo=ubi-9-baseos-rpms --enablerepo=ubi-9-appstream-rpms shadow-utils python3.11 python3.11-devel \
    && microdnf clean all \
    &&  alternatives --install /usr/bin/python python3 /usr/bin/python3.11 1
RUN useradd kserve -m -u 1000 -d /home/kserve

COPY --from=odh-builder --chown=kserve:kserve third_party third_party
COPY --from=odh-builder --chown=kserve:kserve $VIRTUAL_ENV $VIRTUAL_ENV
COPY --from=odh-builder storage storage
COPY ./storage-initializer /storage-initializer

RUN chmod +x /storage-initializer/scripts/initializer-entrypoint
RUN mkdir /work
WORKDIR /work

# Set a writable /mnt folder to avoid permission issue on Huggingface download. See https://huggingface.co/docs/hub/spaces-sdks-docker#permissions
RUN chown -R kserve:kserve /mnt
USER 1000
ENTRYPOINT ["/storage-initializer/scripts/initializer-entrypoint"]

# ============================================================
# RHOAI Build
# ============================================================
ARG VENV_PATH=/prod_venv

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS rhoai-builder

# Install Python and dependencies
RUN microdnf install -y \
    python3.11 \
       python3.11-pip python3.11-devel gcc libffi-devel openssl-devel krb5-workstation krb5-libs krb5-devel && \
    if [ "$(uname -m)" = "s390x" ] || [ "$(uname -m)" = "ppc64le" ]; then \
       echo "Installing packages" && \
       microdnf install -y gcc-c++ cmake perl git && \
       curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y ; \
    fi \
    && microdnf clean all \
    && alternatives --install /usr/bin/unversioned-python python /usr/bin/python3.11 1

# Install uv
RUN /usr/bin/pip3.11 install --no-cache-dir uv

# Activate virtual env
ARG VENV_PATH
ENV VIRTUAL_ENV=${VENV_PATH}
RUN /usr/bin/python3.11 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY storage/pyproject.toml storage/uv.lock storage/

# Install hf_xet from source for s390x and ppc64le
RUN if [ "$(uname -m)" = "s390x" ] || [ "$(uname -m)" = "ppc64le" ]; then \
       export PATH=/root/.cargo/bin:$PATH  && \
       export HF_XET_VERSION=$(uv pip show hf-xet 2>/dev/null | awk '/Version/ {print $2}') && \
       git clone https://github.com/huggingface/xet-core.git && \
       cd xet-core/hf_xet && git checkout v${HF_XET_VERSION} && \
       sed -i '/python-source = "python"/d' pyproject.toml && \
       pip install maturin && \
       maturin build --release --out /hf_xet/wheels/ ; \
    fi

RUN cd storage && \
    if [ "$(uname -m)" = "s390x" ] || [ "$(uname -m)" = "ppc64le" ]; then \
       export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=true && \
       uv pip install /hf_xet/wheels/*.whl ; \
    fi && \
    uv sync --active --no-cache

COPY storage storage
RUN cd storage && uv pip install . --no-cache

RUN uv pip install --no-cache krbcontext==0.10 hdfs~=2.6.0 requests-kerberos==0.14.0

########################################################################
# Runtime
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS rhoai-prod

# Activate virtual env
ARG VENV_PATH
ENV VIRTUAL_ENV=${VENV_PATH}
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN microdnf install -y  \
        shadow-utils python3.11 \
    &&  microdnf clean all \
    && alternatives --install /usr/bin/unversioned-python python /usr/bin/python3.11 1

RUN useradd kserve -m -u 1000 -d /home/kserve && chgrp -R 0 /home/kserve && chmod -R g+rwx /home/kserve

COPY --from=rhoai-builder --chown=kserve:kserve $VIRTUAL_ENV $VIRTUAL_ENV
COPY --from=rhoai-builder storage storage
COPY ./storage-initializer /storage-initializer

# Remove kserve manifest and not needed files from final image, this can lead to false positives in regards to
# CVEs since there are optional libraries which are not installed by storage-initializer
RUN rm -rf /storage/{*.toml,Makefile,*.lock,requirements.txt,setup.cfg,docs,git-push.sh,test,test-requirements.txt,tox.ini}
# clean hidden files/directories
RUN cd /storage && rm -rf .??*

RUN chmod +x /storage-initializer/scripts/initializer-entrypoint
RUN mkdir /work
WORKDIR /work

# Set a writable /mnt folder to avoid permission issue on Huggingface download. See https://huggingface.co/docs/hub/spaces-sdks-docker#permissions
RUN chown -R kserve:kserve /mnt
ENV HOME=/home/kserve
ENV HF_HOME=/home/kserve
USER 1000
ENTRYPOINT ["/storage-initializer/scripts/initializer-entrypoint"]

LABEL com.redhat.component="odh-kserve-storage-initializer" \
      name="odh-kserve-storage-initializer" \
      description="odh-kserve-storage-initializer" \
      summary="odh-kserve-storage-initializer" \
      io.k8s.display-name="odh-kserve-storage-initializer" \
      io.k8s.description="odh-kserve-storage-initializer"

# ============================================================
# Stage selector – picks the build based on BUILD_MODE
# ============================================================
FROM ${odh-prod} AS odh-output
FROM ${rhoai-prod} AS rhoai-output

ARG BUILD_MODE=ODH
FROM ${BUILD_MODE}-output AS final
