apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
    pac.test.appstudio.openshift.io/log-url: https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/open-data-hub-tenant/pipelinerun/group-testing-for-operator-tvlhn
    results.tekton.dev/childReadyForDeletion: "true"
    results.tekton.dev/record: open-data-hub-tenant/results/ade506b4-eed9-4414-bac1-b6fb431b801d/records/ade506b4-eed9-4414-bac1-b6fb431b801d
    results.tekton.dev/result: open-data-hub-tenant/results/ade506b4-eed9-4414-bac1-b6fb431b801d
    test.appstudio.openshift.io/group-test-info: '[{"namespace":"open-data-hub-tenant","component":"feast-operator-poc","buildPipelineRun":"feast-operator-poc-on-pull-request-kr5xr","snapshot":"poc-kwbf5","repoUrl":"https://github.com/rhoai-rhtap/feast","pullRequestNumber":"3"},{"namespace":"open-data-hub-tenant","component":"feature-server-poc","buildPipelineRun":"feature-server-poc-on-pull-request-n9mtb","snapshot":"poc-xsgc7","repoUrl":"https://github.com/rhoai-rhtap/feast","pullRequestNumber":"3"},{"namespace":"open-data-hub-tenant","component":"odh-ci-operator-rhoai-rhtap","buildPipelineRun":"odh-ci-operator-rhoai-rhtap-on-pull-request-sk4v8","snapshot":"poc-f288w","repoUrl":"https://github.com/rhoai-rhtap/opendatahub-operator","pullRequestNumber":"34"}]'
    test.appstudio.openshift.io/pr-group: poc
    test.appstudio.openshift.io/status: '[{"scenario":"group-testing","status":"Pending","lastUpdateTime":"2026-01-21T09:20:30.933245688Z","details":"Pending"},{"scenario":"group-testing-for-operator","status":"Pending","lastUpdateTime":"2026-01-21T09:20:30.933247008Z","details":"Pending"}]'
  creationTimestamp: "2026-01-21T09:20:31Z"
  finalizers:
  - results.tekton.dev/pipelinerun
  - chains.tekton.dev/pipelinerun
  generateName: group-testing-for-operator-
  generation: 2
  labels:
    appstudio.openshift.io/application: poc
    appstudio.openshift.io/snapshot: poc-t55t7
    kueue.x-k8s.io/priority-class: konflux-default
    kueue.x-k8s.io/queue-name: pipelines-queue
    pac.test.appstudio.openshift.io/event-type: on-comment
    pipelines.appstudio.openshift.io/type: test
    tekton.dev/pipeline: odh-pr-test
    test.appstudio.openshift.io/pr-group-sha: 18889a721a537ee1d9f6de4268a9ccf9f3e59bfebac6441f393996fa66ac80
    test.appstudio.openshift.io/scenario: group-testing-for-operator
    test.appstudio.openshift.io/type: group
  name: group-testing-for-operator-tvlhn
  namespace: open-data-hub-tenant
  ownerReferences:
  - apiVersion: appstudio.redhat.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Snapshot
    name: poc-t55t7
    uid: add8febb-2f60-460e-ad11-762c6f44fafe
  resourceVersion: "6794475459"
  uid: ade506b4-eed9-4414-bac1-b6fb431b801d
spec:
  params:
  - name: SNAPSHOT
    value: '{"application":"poc","components":[{"name":"codeflare-ci-operator","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/codeflare-ci-operator@sha256:446517c4823df70c4f52a0dac74938bd6e168efa58185aef4cea1c90ba5d85d3","source":{"git":{"url":"https://github.com/rhoai-rhtap/codeflare-operator","revision":"c09ac18a3ba1fb3ae1530157882e523831dc9d8a","dockerfileUrl":"Dockerfile"}}},{"name":"feast-operator-poc","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/feast-operator-poc@sha256:cc1cae274471f68cdbeb1132641a4b771a0b131e0c89b46882dd9023df521be8","source":{"git":{"url":"https://github.com/rhoai-rhtap/feast","revision":"03f89001716cf7c1a01a9602bc5ff21073a8a9a9"}}},{"name":"odh-ci-operator","containerImage":"quay.io/opendatahub/opendatahub-operator@sha256:5a040367eeb6f8e3d47563f6f65b35edcc93a2694029e4d758ce49f45437f734","source":{"git":{"url":"https://github.com/opendatahub-io/opendatahub-operator","revision":"a0778e5a9f1ec5073bbd7811d68aa3a91050b7cc","dockerfileUrl":"Dockerfiles/Dockerfile"}}},{"name":"odh-ci-operator-bundle","containerImage":"quay.io/opendatahub/opendatahub-operator-bundle@sha256:1ad8af30fa90111d830c9c975733ac0aad03473c2c274f69fd093897c697a1b8","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"9fbc18d7bfeff75c6f7eab87cd329cf1c262fac3","dockerfileUrl":"bundle/Dockerfile"}}},{"name":"component-1","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/component-1@sha256:345950208022855fe4a5bd05051b2497fe0126f2126ff30fb2ebe1a5b3915834","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"140e8758527e0a55552e98588555259ccd375ba4","dockerfileUrl":"Dockerfile"}}},{"name":"component-2","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/component-2@sha256:e9e631f92eaf2dcab0c70739c38ce2e649319efd8c74dc28bdda63c33200a68d","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"1b0ef05360ce713fa71ba4f70c867864f1dc2e54","dockerfileUrl":"Dockerfile"}}},{"name":"feature-server-poc","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/feature-server-poc@sha256:613c8a1b1e495f6b4bfe9ac696db3ed6c1dfa637137d23b2417bd0b38b93bca6","source":{"git":{"url":"https://github.com/rhoai-rhtap/feast","revision":"03f89001716cf7c1a01a9602bc5ff21073a8a9a9"}}},{"name":"odh-ci-fbc-fragment","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/odh-ci-fbc-fragment@sha256:d57d76291a936b96420e235f53337cbd875a9153e328c1a0236330f5bfc2e133","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"8d4c702d06496795dbd5a56df9814a843ccd4da0","context":"catalog/v4.20","dockerfileUrl":"Dockerfile"}}},{"name":"odh-ci-operator-rhoai-rhtap","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/odh-ci-operator-rhoai-rhtap@sha256:df18a9e9671c307709f338ad4ec678440cb49fa6a86b954b093de40f4ba7900a","source":{"git":{"url":"https://github.com/rhoai-rhtap/opendatahub-operator","revision":"e59d6656e486a2af29681ce0a8a5b47bdf092265"}}}],"artifacts":{}}'
  pipelineRef:
    params:
    - name: url
      value: https://github.com/opendatahub-io/odh-konflux-central
    - name: revision
      value: konflux-poc
    - name: pathInRepo
      value: integration-tests/template/pr-group-testing-pipeline.yaml
    resolver: git
  taskRunTemplate:
    podTemplate:
      nodeSelector:
        konflux-ci.dev/workload: konflux-tenants
      tolerations:
      - effect: NoSchedule
        key: konflux-ci.dev/workload
        operator: Equal
        value: konflux-tenants
    serviceAccountName: konflux-integration-runner
  timeouts:
    finally: 2h0m0s
    pipeline: 6h0m0s
    tasks: 4h0m0s
status:
  childReferences:
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: group-testing-for-operator-tvlhn-parse-metadata
    pipelineTaskName: parse-metadata
  - apiVersion: tekton.dev/v1
    kind: TaskRun
    name: group-testing-for-operator-tvlhn-test-snapshot-component
    pipelineTaskName: test-snapshot-component
  completionTime: "2026-01-21T09:21:24Z"
  conditions:
  - lastTransitionTime: "2026-01-21T09:21:24Z"
    message: 'Tasks Completed: 2 (Failed: 0, Cancelled 0), Skipped: 0'
    reason: Succeeded
    status: "True"
    type: Succeeded
  pipelineSpec:
    description: "An integration test which provisions an ephemeral Hypershift cluster,
      deploys opendatahub-operator \nfrom a Konflux snapshot and runs the e2e tests
      against it.\n"
    params:
    - description: Snapshot of the application
      name: SNAPSHOT
      type: string
    tasks:
    - name: parse-metadata
      params:
      - name: SNAPSHOT
        value: '{"application":"poc","components":[{"name":"codeflare-ci-operator","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/codeflare-ci-operator@sha256:446517c4823df70c4f52a0dac74938bd6e168efa58185aef4cea1c90ba5d85d3","source":{"git":{"url":"https://github.com/rhoai-rhtap/codeflare-operator","revision":"c09ac18a3ba1fb3ae1530157882e523831dc9d8a","dockerfileUrl":"Dockerfile"}}},{"name":"feast-operator-poc","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/feast-operator-poc@sha256:cc1cae274471f68cdbeb1132641a4b771a0b131e0c89b46882dd9023df521be8","source":{"git":{"url":"https://github.com/rhoai-rhtap/feast","revision":"03f89001716cf7c1a01a9602bc5ff21073a8a9a9"}}},{"name":"odh-ci-operator","containerImage":"quay.io/opendatahub/opendatahub-operator@sha256:5a040367eeb6f8e3d47563f6f65b35edcc93a2694029e4d758ce49f45437f734","source":{"git":{"url":"https://github.com/opendatahub-io/opendatahub-operator","revision":"a0778e5a9f1ec5073bbd7811d68aa3a91050b7cc","dockerfileUrl":"Dockerfiles/Dockerfile"}}},{"name":"odh-ci-operator-bundle","containerImage":"quay.io/opendatahub/opendatahub-operator-bundle@sha256:1ad8af30fa90111d830c9c975733ac0aad03473c2c274f69fd093897c697a1b8","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"9fbc18d7bfeff75c6f7eab87cd329cf1c262fac3","dockerfileUrl":"bundle/Dockerfile"}}},{"name":"component-1","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/component-1@sha256:345950208022855fe4a5bd05051b2497fe0126f2126ff30fb2ebe1a5b3915834","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"140e8758527e0a55552e98588555259ccd375ba4","dockerfileUrl":"Dockerfile"}}},{"name":"component-2","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/component-2@sha256:e9e631f92eaf2dcab0c70739c38ce2e649319efd8c74dc28bdda63c33200a68d","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"1b0ef05360ce713fa71ba4f70c867864f1dc2e54","dockerfileUrl":"Dockerfile"}}},{"name":"feature-server-poc","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/feature-server-poc@sha256:613c8a1b1e495f6b4bfe9ac696db3ed6c1dfa637137d23b2417bd0b38b93bca6","source":{"git":{"url":"https://github.com/rhoai-rhtap/feast","revision":"03f89001716cf7c1a01a9602bc5ff21073a8a9a9"}}},{"name":"odh-ci-fbc-fragment","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/odh-ci-fbc-fragment@sha256:d57d76291a936b96420e235f53337cbd875a9153e328c1a0236330f5bfc2e133","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"8d4c702d06496795dbd5a56df9814a843ccd4da0","context":"catalog/v4.20","dockerfileUrl":"Dockerfile"}}},{"name":"odh-ci-operator-rhoai-rhtap","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/odh-ci-operator-rhoai-rhtap@sha256:df18a9e9671c307709f338ad4ec678440cb49fa6a86b954b093de40f4ba7900a","source":{"git":{"url":"https://github.com/rhoai-rhtap/opendatahub-operator","revision":"e59d6656e486a2af29681ce0a8a5b47bdf092265"}}}],"artifacts":{}}'
      taskRef:
        params:
        - name: url
          value: https://github.com/konflux-ci/integration-examples
        - name: revision
          value: main
        - name: pathInRepo
          value: tasks/test_metadata.yaml
        resolver: git
    - description: Placeholder task that prints the Snapshot and outputs standard
        TEST_OUTPUT
      name: test-snapshot-component
      params:
      - name: SNAPSHOT
        value: '{"application":"poc","components":[{"name":"codeflare-ci-operator","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/codeflare-ci-operator@sha256:446517c4823df70c4f52a0dac74938bd6e168efa58185aef4cea1c90ba5d85d3","source":{"git":{"url":"https://github.com/rhoai-rhtap/codeflare-operator","revision":"c09ac18a3ba1fb3ae1530157882e523831dc9d8a","dockerfileUrl":"Dockerfile"}}},{"name":"feast-operator-poc","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/feast-operator-poc@sha256:cc1cae274471f68cdbeb1132641a4b771a0b131e0c89b46882dd9023df521be8","source":{"git":{"url":"https://github.com/rhoai-rhtap/feast","revision":"03f89001716cf7c1a01a9602bc5ff21073a8a9a9"}}},{"name":"odh-ci-operator","containerImage":"quay.io/opendatahub/opendatahub-operator@sha256:5a040367eeb6f8e3d47563f6f65b35edcc93a2694029e4d758ce49f45437f734","source":{"git":{"url":"https://github.com/opendatahub-io/opendatahub-operator","revision":"a0778e5a9f1ec5073bbd7811d68aa3a91050b7cc","dockerfileUrl":"Dockerfiles/Dockerfile"}}},{"name":"odh-ci-operator-bundle","containerImage":"quay.io/opendatahub/opendatahub-operator-bundle@sha256:1ad8af30fa90111d830c9c975733ac0aad03473c2c274f69fd093897c697a1b8","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"9fbc18d7bfeff75c6f7eab87cd329cf1c262fac3","dockerfileUrl":"bundle/Dockerfile"}}},{"name":"component-1","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/component-1@sha256:345950208022855fe4a5bd05051b2497fe0126f2126ff30fb2ebe1a5b3915834","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"140e8758527e0a55552e98588555259ccd375ba4","dockerfileUrl":"Dockerfile"}}},{"name":"component-2","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/component-2@sha256:e9e631f92eaf2dcab0c70739c38ce2e649319efd8c74dc28bdda63c33200a68d","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"1b0ef05360ce713fa71ba4f70c867864f1dc2e54","dockerfileUrl":"Dockerfile"}}},{"name":"feature-server-poc","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/feature-server-poc@sha256:613c8a1b1e495f6b4bfe9ac696db3ed6c1dfa637137d23b2417bd0b38b93bca6","source":{"git":{"url":"https://github.com/rhoai-rhtap/feast","revision":"03f89001716cf7c1a01a9602bc5ff21073a8a9a9"}}},{"name":"odh-ci-fbc-fragment","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/odh-ci-fbc-fragment@sha256:d57d76291a936b96420e235f53337cbd875a9153e328c1a0236330f5bfc2e133","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"8d4c702d06496795dbd5a56df9814a843ccd4da0","context":"catalog/v4.20","dockerfileUrl":"Dockerfile"}}},{"name":"odh-ci-operator-rhoai-rhtap","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/odh-ci-operator-rhoai-rhtap@sha256:df18a9e9671c307709f338ad4ec678440cb49fa6a86b954b093de40f4ba7900a","source":{"git":{"url":"https://github.com/rhoai-rhtap/opendatahub-operator","revision":"e59d6656e486a2af29681ce0a8a5b47bdf092265"}}}],"artifacts":{}}'
      runAfter:
      - parse-metadata
      taskSpec:
        metadata: {}
        params:
        - description: The JSON string of the Snapshot under test
          name: SNAPSHOT
          type: string
        spec: null
        steps:
        - computeResources: {}
          env:
          - name: SNAPSHOT
            value: '{"application":"poc","components":[{"name":"codeflare-ci-operator","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/codeflare-ci-operator@sha256:446517c4823df70c4f52a0dac74938bd6e168efa58185aef4cea1c90ba5d85d3","source":{"git":{"url":"https://github.com/rhoai-rhtap/codeflare-operator","revision":"c09ac18a3ba1fb3ae1530157882e523831dc9d8a","dockerfileUrl":"Dockerfile"}}},{"name":"feast-operator-poc","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/feast-operator-poc@sha256:cc1cae274471f68cdbeb1132641a4b771a0b131e0c89b46882dd9023df521be8","source":{"git":{"url":"https://github.com/rhoai-rhtap/feast","revision":"03f89001716cf7c1a01a9602bc5ff21073a8a9a9"}}},{"name":"odh-ci-operator","containerImage":"quay.io/opendatahub/opendatahub-operator@sha256:5a040367eeb6f8e3d47563f6f65b35edcc93a2694029e4d758ce49f45437f734","source":{"git":{"url":"https://github.com/opendatahub-io/opendatahub-operator","revision":"a0778e5a9f1ec5073bbd7811d68aa3a91050b7cc","dockerfileUrl":"Dockerfiles/Dockerfile"}}},{"name":"odh-ci-operator-bundle","containerImage":"quay.io/opendatahub/opendatahub-operator-bundle@sha256:1ad8af30fa90111d830c9c975733ac0aad03473c2c274f69fd093897c697a1b8","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"9fbc18d7bfeff75c6f7eab87cd329cf1c262fac3","dockerfileUrl":"bundle/Dockerfile"}}},{"name":"component-1","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/component-1@sha256:345950208022855fe4a5bd05051b2497fe0126f2126ff30fb2ebe1a5b3915834","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"140e8758527e0a55552e98588555259ccd375ba4","dockerfileUrl":"Dockerfile"}}},{"name":"component-2","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/component-2@sha256:e9e631f92eaf2dcab0c70739c38ce2e649319efd8c74dc28bdda63c33200a68d","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"1b0ef05360ce713fa71ba4f70c867864f1dc2e54","dockerfileUrl":"Dockerfile"}}},{"name":"feature-server-poc","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/feature-server-poc@sha256:613c8a1b1e495f6b4bfe9ac696db3ed6c1dfa637137d23b2417bd0b38b93bca6","source":{"git":{"url":"https://github.com/rhoai-rhtap/feast","revision":"03f89001716cf7c1a01a9602bc5ff21073a8a9a9"}}},{"name":"odh-ci-fbc-fragment","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/odh-ci-fbc-fragment@sha256:d57d76291a936b96420e235f53337cbd875a9153e328c1a0236330f5bfc2e133","source":{"git":{"url":"https://github.com/opendatahub-io/ODH-Build-Config","revision":"8d4c702d06496795dbd5a56df9814a843ccd4da0","context":"catalog/v4.20","dockerfileUrl":"Dockerfile"}}},{"name":"odh-ci-operator-rhoai-rhtap","containerImage":"quay.io/redhat-user-workloads/open-data-hub-tenant/odh-ci-operator-rhoai-rhtap@sha256:df18a9e9671c307709f338ad4ec678440cb49fa6a86b954b093de40f4ba7900a","source":{"git":{"url":"https://github.com/rhoai-rhtap/opendatahub-operator","revision":"e59d6656e486a2af29681ce0a8a5b47bdf092265"}}}],"artifacts":{}}'
          - name: SNAPSHOT_URL
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/source-repo-url']
          - name: SNAPSHOT_SHA
            valueFrom:
              fieldRef:
                fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/sha']
          image: quay.io/konflux-ci/konflux-test:stable
          name: test-snapshot-component
          script: |
            #!/bin/bash
            set -e
            echo "SNAPSHOT_URL=${SNAPSHOT_URL}"
            echo "SNAPSHOT_SHA=${SNAPSHOT_SHA}"

            components=$(jq -c '.components[]' <<< "${SNAPSHOT}")
            snapshotUrlUrlWithoutSuffix=$(echo $SNAPSHOT_URL | sed 's/\.git$//')
            echo "snapshotUrlUrlWithoutSuffix=${snapshotUrlUrlWithoutSuffix}"

            while read components
            do
              componentUrl=$(echo "$components" | jq -r '.source.git.url')
              echo "componentUrl=${componentUrl}"

              componentUrlWithoutSuffix=$(echo $componentUrl | sed 's/\.git$//')
              echo "componentUrlWithoutSuffix=${componentUrlWithoutSuffix}"

              name=$(echo "$components" | jq -r '.name')
              echo "name=${name}"

              componentSha=$(echo "$components" | jq -r '.source.git.revision')
              echo "componentSha=${componentSha}"

                # Check if component git url equals to snapshot git url, if yes check if the snapshot SHA equals to component SHA
                if [[ $componentUrlWithoutSuffix == $snapshotUrlUrlWithoutSuffix ]]; then
                    if [[ $componentSha != $SNAPSHOT_SHA ]]; then
                    echo "FAIL: Component $name has different SHA: $componentSha than the snapshot, SHA: $SNAPSHOT_SHA."
                    exit 1
                    fi
                fi
              echo "SUCCESS: Component $name matches snapshot SHA."
            done < <(echo "$components")
          workingDir: /workspace
  spanContext:
    traceparent: 00-06543f07337b5ef031158f9f883a4014-6f37e21593a865b9-01
  startTime: "2026-01-21T09:20:38Z"
