---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: early-gate-build-pipeline
spec:
  description: |
    A pipeline to build, operator, bundle and FBC quickly for a new piece of code in the feature branch to be tested quickly before pushing to stable
  params:
    - description: List of components in the group
      name: group-components
      type: string
    - description: List of components in the group
      name: operator-git-url
      type: string
    - description: List of components in the group
      name: operator-revision
      type: string
  tasks:
    - name: generate-snapshot
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: COMPONENTS
          value: $(params.group-components)
      workspaces:
      - name: basic-auth
        workspace: git-auth
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/red-hat-data-services/rhoai-konflux-tasks.git
        - name: revision
          value: main
        - name: pathInRepo
          value: konflux-tekton-tasks/generate-snapshot-for-group-testing/0.1/generate-snapshot-for-group-testing.yaml
    - name: audit-snapshot
      runAfter:
        - generate-snapshot
      params:
        - name: COMPONENTS
          value: $(params.group-components)
      taskSpec:
        params:
          - name: COMPONENTS
            description: List of components in the group
        results:
        - name: pull-request-author
        - name: pull-request-number
        - name: git-repo
        - name: git-org
        - name: git-revision
        - name: snapshot-contains-operator
        steps:
          - name: audit-snapshot
            image: quay.io/konflux-ci/konflux-test:stable
            workingDir: /workspace
            env:
              - name: SNAPSHOT
                value: $(tasks.generate-snapshot.results.SNAPSHOT)
              - name: COMPONENTS
                value: $(params.COMPONENTS)
              - name: PR_AUTHOR
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pipelinesascode.tekton.dev/sender']
              - name: PR_NUMBER
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['pipelinesascode.tekton.dev/pull-request']
              - name: GIT_REPO
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pipelinesascode.tekton.dev/url-repository']
              - name: GIT_ORG
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pipelinesascode.tekton.dev/url-org']
              - name: GIT_REVISION
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pipelinesascode.tekton.dev/sha']
            script: |
              #!/bin/bash
              set -e
              echo "SNAPSHOT=${SNAPSHOT}"
              SNAPSHOT_CONTAINS_ODH_OPERATOR=false
              # Parse JSON and iterate through each component
              while IFS= read -r row; do
                  COMPONENT_NAME=$(echo "$row" | base64 -d | jq -r '.key')
                  IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name].image' <<< "${SNAPSHOT}")
                  if [[ "${COMPONENT_NAME}" == "odh-operator-ci" ]] && [[ "${IMAGE}" == "quay.io/opendatahub/opendatahub-operator"* ]]; then
                      SNAPSHOT_CONTAINS_ODH_OPERATOR=true
                  fi
                  GIT_COMMIT=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.commit"' <<< "${SNAPSHOT}")
                  GIT_URL=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.url"' <<< "${SNAPSHOT}")
                  echo "${COMPONENT_NAME} IMAGE: ${IMAGE}"
                  echo "GIT_COMMIT=${GIT_COMMIT}"
                  echo "GIT_URL=${GIT_URL}"
              done < <(echo "$COMPONENTS" | jq -r 'to_entries[] | @base64')

              echo -n "${PR_AUTHOR}" > "$(results.pull-request-author.path)"
              echo -n "${PR_NUMBER}" > "$(results.pull-request-number.path)"
              echo -n "${GIT_REPO}" > "$(results.git-repo.path)"
              echo -n "${GIT_ORG}" > "$(results.git-org.path)"
              echo -n "${GIT_REVISION}" > "$(results.git-revision.path)"
              echo -n "${SNAPSHOT_CONTAINS_ODH_OPERATOR}" > "$(results.snapshot-contains-operator.path)"
    - name: clone-operator-repository
      params:
      - name: url
        value: $(params.operator-git-url)
      - name: revision
        value: $(params.operator-revision)
      - name: ociStorage
        value: $(params.output-image).git
      - name: ociArtifactExpiresAfter
        value: $(params.image-expires-after)
      - name: fetchTags
        value: $(params.fetch-git-tags)
      - name: depth
        value: $(params.clone-depth)
      runAfter:
      - init
      taskRef:
        params:
        - name: name
          value: git-clone-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:0a89e1a6304076525e9766f63a4cd006763d21d5aca6863281fc427537a23c6f
        - name: kind
          value: task
        resolver: bundles
      when:
      - input: $(tasks.init.results.build)
        operator: in
        values:
        - "true"
      workspaces:
      - name: basic-auth
        workspace: git-auth
    - name: prefetch-manifests
      params:
      - name: SOURCE_ARTIFACT
        value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      - name: ociStorage
        value: $(params.output-image).prefetch
      - name: ociArtifactExpiresAfter
        value: "1h"
      - name: utilsRepoBranch
        value: $(params.utils-repo-branch)
      - name: buildVersionTag
        value: $(params.build-version-tag)
      runAfter:
      - clone-repository
      taskRef:
        params:
        - name: url
          value: https://github.com/red-hat-data-services/rhoai-konflux-tasks
        - name: revision
          value: "odh"
        - name: pathInRepo
          value: "konflux-tekton-tasks/prefetch-operand-manifests-oci-ta/0.1/prefetch-operand-manifests-oci-ta.yaml"
        resolver: git
      workspaces:
      - name: git-basic-auth
        workspace: git-auth
      - name: netrc
        workspace: netrc
    - name: audit-manifests
      description: audit the collected manifests
      runAfter:
      - prefetch-manifests
      taskSpec:
        volumes:
        - name: workdir
          emptyDir: {}
        stepTemplate:
          volumeMounts:
            - mountPath: /var/workdir
              name: workdir
        steps:
          - name: use-trusted-artifact
            image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:81c4864dae6bb11595f657be887e205262e70086a05ed16ada827fd6391926ac
            args:
              - use
              - $(tasks.prefetch-manifests.results.SOURCE_ARTIFACT)=/var/workdir/source
              - $(tasks.prefetch-manifests.results.CACHI2_ARTIFACT)=/var/workdir/cachi2
          - image: quay.io/rhoai/rhoai-task-toolset:latest
            env:
            - name: SOURCE_ARTIFACT
              value: $(tasks.prefetch-manifests.results.SOURCE_ARTIFACT)
            - name: CACHI2_ARTIFACT
              value: $(tasks.prefetch-manifests.results.CACHI2_ARTIFACT)
            script: |
              echo "SOURCE_ARTIFACT=${SOURCE_ARTIFACT}"
              echo "CACHI2_ARTIFACT=${CACHI2_ARTIFACT}"
              echo "exploring manifests"
              ls /var/workdir/cachi2
              ls /var/workdir/cachi2/prefetched-manifests

              echo "exploring sources"
              ls /var/workdir/source


  workspaces:
  - name: git-auth
    optional: true
