---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: early-gate-build-pipeline
spec:
  description: |
    A pipeline to build, operator, bundle and FBC quickly for a new piece of code in the feature branch to be tested quickly before pushing to stable
  params:
    - description: List of components in the group
      name: group-components
      type: string
  tasks:
    - name: generate-snapshot
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: COMPONENTS
          value: $(params.group-components)
      workspaces:
      - name: basic-auth
        workspace: git-auth
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/red-hat-data-services/rhoai-konflux-tasks.git
        - name: revision
          value: main
        - name: pathInRepo
          value: konflux-tekton-tasks/generate-snapshot-for-group-testing/0.1/generate-snapshot-for-group-testing.yaml
    - name: audit-snapshot
      runAfter:
        - generate-snapshot
      params:
        - name: COMPONENTS
          value: $(params.group-components)
      taskSpec:
        params:
          - name: COMPONENTS
            description: List of components in the group
        results:
        - name: pull-request-author
        - name: pull-request-number
        - name: git-repo
        - name: git-org
        - name: git-revision
        - name: snapshot-contains-operator
        steps:
          - name: audit-snapshot
            image: quay.io/konflux-ci/konflux-test:stable
            workingDir: /workspace
            env:
              - name: SNAPSHOT
                value: $(tasks.generate-snapshot.results.SNAPSHOT)
              - name: COMPONENTS
                value: $(params.COMPONENTS)
              - name: PR_AUTHOR
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pipelinesascode.tekton.dev/sender']
              - name: PR_NUMBER
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['pipelinesascode.tekton.dev/pull-request']
              - name: GIT_REPO
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pipelinesascode.tekton.dev/url-repository']
              - name: GIT_ORG
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pipelinesascode.tekton.dev/url-org']
              - name: GIT_REVISION
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pipelinesascode.tekton.dev/sha']
            script: |
              #!/bin/bash
              set -e
              echo "SNAPSHOT=${SNAPSHOT}"
              SNAPSHOT_CONTAINS_ODH_OPERATOR=false
              # Parse JSON and iterate through each component
              while IFS= read -r row; do
                  COMPONENT_NAME=$(echo "$row" | base64 -d | jq -r '.key')
                  IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name].image' <<< "${SNAPSHOT}")
                  if [[ "${COMPONENT_NAME}" == "odh-operator-ci" ]] && [[ "${IMAGE}" == "quay.io/opendatahub/opendatahub-operator"* ]]; then
                      SNAPSHOT_CONTAINS_ODH_OPERATOR=true
                  fi
                  GIT_COMMIT=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.commit"' <<< "${SNAPSHOT}")
                  GIT_URL=$(jq -r --arg component_name "${COMPONENT_NAME}" '.[$component_name]."git.url"' <<< "${SNAPSHOT}")
                  echo "${COMPONENT_NAME} IMAGE: ${IMAGE}"
                  echo "GIT_COMMIT=${GIT_COMMIT}"
                  echo "GIT_URL=${GIT_URL}"
              done < <(echo "$COMPONENTS" | jq -r 'to_entries[] | @base64')

              echo -n "${PR_AUTHOR}" > "$(results.pull-request-author.path)"
              echo -n "${PR_NUMBER}" > "$(results.pull-request-number.path)"
              echo -n "${GIT_REPO}" > "$(results.git-repo.path)"
              echo -n "${GIT_ORG}" > "$(results.git-org.path)"
              echo -n "${GIT_REVISION}" > "$(results.git-revision.path)"
              echo -n "${SNAPSHOT_CONTAINS_ODH_OPERATOR}" > "$(results.snapshot-contains-operator.path)"
  workspaces:
  - name: git-auth
    optional: true
