ARG BUILD_MODE=ODH

ARG BASE_IMAGE_ODH=registry.access.redhat.com/ubi9/go-toolset:1.25
ARG BASE_IMAGE_RHOAI=registry.access.redhat.com/ubi9/go-toolset:1.25@sha256:8b211cc8793d8013140844e8070aa584a8eb3e4e6e842ea4b03dd9914b1a5dc6
ARG BASE_IMAGE=${BASE_IMAGE_${BUILD_MODE}}
FROM ${BASE_IMAGE} AS builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY . .

# Build
USER root
RUN if [ "$BUILD_MODE" = "RHOAI" ]; then \
      CGO_ENABLED=1 GOOS=linux GO111MODULE=on GOEXPERIMENT=strictfipsruntime go build -tags strictfipsruntime -a -o manager cmd/training-operator.v1/main.go ; \
    else \
      CGO_ENABLED=1 GOOS=linux GO111MODULE=on go build -tags strictfipsruntime -a -o manager cmd/training-operator.v1/main.go ; \
    fi

# Runtime
ARG BASE_IMAGE_1_ODH=registry.access.redhat.com/ubi9/ubi:latest
ARG BASE_IMAGE_1_RHOAI=registry.access.redhat.com/ubi9/ubi-minimal@sha256:83006d535923fcf1345067873524a3980316f51794f01d8655be55d6e9387183
ARG BASE_IMAGE_1=${BASE_IMAGE_1_${BUILD_MODE}}
FROM ${BASE_IMAGE_1} AS runtime

# >>> [ODH] <<<
RUN dnf update -y && dnf install -y bind-utils
# >>> [END ODH] <<<
# >>> [RHOAI] <<<
ARG USER=65532

LABEL com.redhat.component="odh-training-operator-container" \
      name="managed-open-data-hub/odh-training-operator-rhel8" \
      description="Training Operator is a Kubernetes-native project for fine-tuning and scalable distributed training of AI/ML models created with various frameworks such as PyTorch." \
      summary="odh-training-operator" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-training-operator" \
      io.k8s.description="odh-training-operator" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"

RUN microdnf install -y bind-utils
# >>> [END RHOAI] <<<

WORKDIR /
COPY --from=builder /workspace/manager .
# >>> [ODH] <<<
USER 65532:65532
ENTRYPOINT ["/manager"]
# >>> [END ODH] <<<
# >>> [RHOAI] <<<
## Create a non-root user with UID 65532 and switch to it
USER ${USER}:${USER}
ENTRYPOINT ["/manager"]# >>> [END RHOAI] <<<
