---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: target_url == "https://github.com/opendatahub-io/odh-konflux-central"
  name: odh-group-test-feast
  namespace: open-data-hub-tenant
spec:
  params:
  - name: group-components
    value: '{ "feast-operator-poc": "redhat-user-workloads/open-data-hub-tenant/feast-operator-poc", "feature-server-poc": "redhat-user-workloads/open-data-hub-tenant/feature-server-poc" }'
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/opendatahub-io/odh-konflux-central.git
    - name: revision
      value: 2d64aecf3f8439542327e17d23ee78fe28d0b27f
    - name: pathInRepo
      value: integration-tests/template/pr-group-testing-pipeline.yaml