---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: odh-pr-test
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster, deploys opendatahub-operator 
    from a Konflux snapshot and runs the e2e tests against it.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      type: string
  #test
  tasks:
    - name: parse-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/integration-examples
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: test-snapshot-component
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      runAfter:
        - parse-metadata
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
          - name: SNAPSHOT
            description: The JSON string of the Snapshot under test
        steps:
          - name: test-snapshot-component
            image: quay.io/konflux-ci/konflux-test:stable
            workingDir: /workspace
            env:
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
              - name: SNAPSHOT_URL
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/source-repo-url']
              - name: SNAPSHOT_SHA
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['pac.test.appstudio.openshift.io/sha']
            script: |
              #!/bin/bash
              set -e
              echo "SNAPSHOT_URL=${SNAPSHOT_URL}"
              echo "SNAPSHOT_SHA=${SNAPSHOT_SHA}"
              
              components=$(jq -c '.components[]' <<< "${SNAPSHOT}")
              snapshotUrlUrlWithoutSuffix=$(echo $SNAPSHOT_URL | sed 's/\.git$//')
              echo "snapshotUrlUrlWithoutSuffix=${snapshotUrlUrlWithoutSuffix}"
              
              while read components
              do
                componentUrl=$(echo "$components" | jq -r '.source.git.url')
                echo "componentUrl=${componentUrl}"
              
                componentUrlWithoutSuffix=$(echo $componentUrl | sed 's/\.git$//')
                echo "componentUrlWithoutSuffix=${componentUrlWithoutSuffix}"
              
                name=$(echo "$components" | jq -r '.name')
                echo "name=${name}"
              
                componentSha=$(echo "$components" | jq -r '.source.git.revision')
                echo "componentSha=${componentSha}"
              
                  # Check if component git url equals to snapshot git url, if yes check if the snapshot SHA equals to component SHA
                  if [[ $componentUrlWithoutSuffix == $snapshotUrlUrlWithoutSuffix ]]; then
                      if [[ $componentSha != $SNAPSHOT_SHA ]]; then
                      echo "FAIL: Component $name has different SHA: $componentSha than the snapshot, SHA: $SNAPSHOT_SHA."
                      exit 1
                      fi
                  fi
                echo "SUCCESS: Component $name matches snapshot SHA."
              done < <(echo "$components")
        

    - name: find-component-image
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      runAfter:
        - parse-metadata
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
        - name: SNAPSHOT
        steps:
        - image: quay.io/konflux-ci/konflux-test:stable
          workingDir: /workspace
          env:
            - name: SNAPSHOT
              value: $(params.SNAPSHOT)
            - name: COMPONENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['appstudio.openshift.io/component']
          script: |
            #!/bin/sh
    
            # Extract the component container image from the SNAPSHOT JSON data
            COMPONENT_CONTAINER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.components[] | select(.name == $component_name) | .containerImage' <<< "${SNAPSHOT}")
    
            # Log the extracted variable
            echo "  COMPONENT_CONTAINER_IMAGE: ${COMPONENT_CONTAINER_IMAGE}"

    - name: check-prerequisites
      description: check prerequisites if the ITS needs to execute
      runAfter:
        - find-component-image
      taskSpec:
        results:
        - name: event-type
          description: "stores info about event type"
        steps:
        - image: quay.io/konflux-ci/konflux-test:stable
          env:
            - name: EVENT_TYPE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['pac.test.appstudio.openshift.io/event-type']
          script: |
            #!/bin/bash
            set -e
            echo "EVENT_TYPE=${EVENT_TYPE}"
            echo -n "${EVENT_TYPE}" > $(results.event-type.path)